import { Language, ProfanityWordConfig } from "@/types/profanity";

export const PROFANITY_CONFIG: ProfanityWordConfig[] = [
  {
    language: "en",
    words: new Set([
      "arse",
      "arsehead",
      "arsehole",
      "ass",
      "assfuck",
      "asshole",
      "assholehead",
      "asslick",
      "bitch",
      "bollocks",
      "brotherfucker",
      "bugger",
      "bullfuck",
      "bullshit",
      "child-fucker",
      "Christ on a bike",
      "Christ on a cracker",
      "cock",
      "cocksucker",
      "crap",
      "cunt",
      "dammit",
      "damn",
      "damned",
      "damn it",
      "dick",
      "dick-head",
      "dickhead",
      "dumb ass",
      "dumb-ass",
      "dumbass",
      "dyke",
      "fag",
      "faggot",
      "father-fucker",
      "fatherfucker",
      "fuck",
      "fucked",
      "fucker",
      "fucking",
      "god dammit",
      "goddammit",
      "God damn",
      "god damn",
      "goddamn",
      "Goddamn",
      "goddamned",
      "goddamnit",
      "godsdamn",
      "hell",
      "holy shit",
      "horseshit",
      "in shit",
      "jackarse",
      "jack-ass",
      "jackass",
      "Jesus Christ",
      "Jesus fuck",
      "Jesus Harold Christ",
      "Jesus H. Christ",
      "Jesus, Mary and Joseph",
      "Jesus wept",
      "kike",
      "mental",
      "mother fucker",
      "mother-fucker",
      "motherfucker",
      "nigga",
      "nigger",
      "nigra",
      "pigfucker",
      "piss",
      "prick",
      "pussy",
      "shit",
      "shit ass",
      "shite",
      "sibling fucker",
      "sisterfuck",
      "sisterfucker",
      "slut",
      "son of a bitch",
      "son of a whore",
      "spastic",
      "sweet Jesus",
      "tranny",
      "twat",
      "wanker",
    ]),
    phrases: new Set(["bull fuck", "chink chong", "dickbrain", "dog brain"]),
    patterns: [
      /\b(ass|bull)\s*fuck\b/gi,
      /\bdick\s*brain\b/gi,
      /\bdog\s*brain\b/gi,
      /\bchink\s*chong\b/gi,
    ],
  },
  {
    language: "vi",
    words: new Set([
      "buồi",
      "cặc",
      "chịch",
      "cứt",
      "dái",
      "đít",
      "đĩ",
      "địt",
      "đụ",
      "lồn",
      "óc",
    ]),
    phrases: new Set([
      "âm đạo",
      "dương vật",
      "chó chết",
      "chó đẻ",
      "hột le",
      "súc sinh",
      "súc vật",
      "tinh dịch",
      "tinh trùng",
      "xuất tinh",
    ]),
    patterns: [
      /\b(chó\s*(chết|đẻ))\b/gi,
      /\b(súc\s*(sinh|vật))\b/gi,
      /\b(tinh\s*(dịch|trùng))\b/gi,
    ],
  },
];

// Optimized flattening with language context
export const CUSTOM_PROFANITY_WORDS = new Map<Language, string[]>(
  PROFANITY_CONFIG.map((config) => [
    config.language,
    [...config.words, ...config.phrases],
  ]),
);
