import { Language, ProfanityWordConfig } from "@/types/profanity";

export const PROFANITY_CONFIG: ProfanityWordConfig[] = [
  {
    language: "en",
    words: new Set([
      "arse",
      "arsefuck",
      "arsehole",
      "arseholehead",
      "asslick",
      "ass",
      "asshole",
      "assholehead",
      "asslick",
      "bitch",
      "bollocks",
      "bugger",
      "cock",
      "cocksucker",
      "cunt",
      "dick",
      "dyke",
      "fag",
      "faggot",
      "fuck",
      "fucked",
      "fucker",
      "fucking",
      "hitler",
      "horseshit",
      "jackarse",
      "kike",
      "nazi",
      "nigga",
      "nigger",
      "nigra",
      "prick",
      "pussy",
      "slut",
      "spastic",
      "tranny",
      "twat",
      "wanker",
    ]),
    phrases: new Set([
      "Christ on a bike",
      "Christ on a cracker",
      "Jesus Christ",
      "Jesus fuck",
      "Jesus Harold Christ",
      "Jesus H. Christ",
      "Jesus, Mary and Joseph",
      "Jesus wept",
      "sweet Jesus",
    ]),
    patterns: [
      /\b(ass|bull)\s*(fuck|fucking|fucked|fucker)\b/gi,
      /\bbrother[- ]?(fuck|fucking|fucked|fucker)\b/gi,
      /\bdick[- ]?brain\b/gi,
      /\bdick[- ]?head\b/gi,
      /\bdog[- ]?brain\b/gi,
      /\bching[- ]?chong\b/gi,
      /\bchild[- ]?(fuck|fucking|fucked|fucker)\b/gi,
      /\bdumb[- ]?ass\b/gi,
      /\bfather[- ]?(fuck|fucking|fucked|fucker)\b/gi,
      /\bgod ?damn(ed|it)?\b/gi,
      /\bjack[- ]?ass\b/gi,
      /\bmother[- ]?(fuck|fucking|fucked|fucker)\b/gi,
      /\bson of a (bitch|whore)\b/gi,
      /\bsibling[- ]?(fuck|fucking|fucked|fucker)\b/gi,
      /\bsister[- ]?(fuck|fucking|fucked|fucker)?\b/gi,
    ],
  },
  {
    language: "vi",
    words: new Set([
      "buồi",
      "cặc",
      "chịch",
      "cứt",
      "dái",
      "đít",
      "đĩ",
      "địt",
      "đụ",
      "lồn",
      "óc",
    ]),
    phrases: new Set([
      "âm đạo",
      "dương vật",
      "chó chết",
      "chó đẻ",
      "hột le",
      "súc sinh",
      "súc vật",
      "tinh dịch",
      "tinh trùng",
      "xuất tinh",
    ]),
    patterns: [
      /\b(chó\s*(chết|đẻ))\b/gi,
      /\b(súc\s*(sinh|vật))\b/gi,
      /\b(tinh\s*(dịch|trùng))\b/gi,
    ],
  },
];

// Optimized flattening with language context
export const CUSTOM_PROFANITY_WORDS = new Map<Language, string[]>(
  PROFANITY_CONFIG.map((config) => [
    config.language,
    [...config.words, ...config.phrases],
  ]),
);
